### 1. Test Inscription
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "recruteur@test.com",
  "password": "password123",
  "role": "RECRUITER"
}

### 2. Test Connexion
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "recruteur@test.com",
  "password": "password123"
}

### 3. Test Session /me (Remplace VOTRE_TOKEN_ICI par le token reçu au Login)
GET http://localhost:5000/api/auth/me
Authorization: Bearer VOTRE_TOKEN_ICI