'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import AdminDataTable, { AdminColumn } from './data/AdminDataTable';
import AdminFilters from './data/AdminFilters';
import AdminPagination from './data/AdminPagination';
import AdminPageHeader from './layout/AdminPageHeader';
import AdminButton from './ui/AdminButton';
import { getAdminResource, rejectAdminApplication, deleteAdminApplication, setAdminUserBlocked, deleteAdminUser, setCompanyApproval } from '@/lib/admin-api';
import Link from 'next/link';

type Row = Record<string, unknown> & { id?: string | number; userId?: string | number; isBlocked?: boolean; isApproved?: boolean };
type ResourceConfig = { title: string; description: string; endpoint: string; columns: Array<{ key: string; label: string }>; filters: Array<{ key: string; label: string; options?: Array<{ label: string; value: string }> }>; empty: string; action?: string };

const configs: Record<string, ResourceConfig> = {
  candidates: { title: 'Candidats', description: 'Consultez et supervisez les profils candidats de JOBSINC.', endpoint: 'candidates', columns: [{ key: 'name', label: 'Nom' }, { key: 'email', label: 'Email' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Inscription' }, { key: 'lastActivity', label: 'Dernière activité' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Actif', value: 'active' }, { label: 'Suspendu', value: 'suspended' }] }], empty: 'Aucun candidat trouvé.' },
  employees: { title: 'Employés', description: 'Supervisez les employés et leurs rattachements entreprise.', endpoint: 'employees', columns: [{ key: 'name', label: 'Nom' }, { key: 'companyName', label: 'Entreprise' }, { key: 'role', label: 'Rôle' }, { key: 'status', label: 'Statut' }, { key: 'lastActivity', label: 'Dernière activité' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Actif', value: 'active' }, { label: 'Suspendu', value: 'suspended' }] }], empty: 'Aucun employé trouvé.' },
  companies: { title: 'Entreprises / recruteurs', description: 'Gérez les organisations présentes sur la plateforme.', endpoint: 'companies', columns: [{ key: 'name', label: 'Entreprise' }, { key: 'sector', label: 'Secteur' }, { key: 'location', label: 'Localisation' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Inscription' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Actif', value: 'active' }, { label: 'En attente', value: 'pending' }] }], empty: 'Aucune entreprise trouvée.' },
  administrators: { title: 'Administrateurs', description: 'Visualisez les comptes autorisés à administrer JOBSINC.', endpoint: 'administrators', columns: [{ key: 'name', label: 'Nom' }, { key: 'email', label: 'Email' }, { key: 'role', label: 'Rôle' }, { key: 'status', label: 'Statut' }, { key: 'lastActivity', label: 'Dernière activité' }], filters: [{ key: 'role', label: 'Rôle', options: [{ label: 'Administrateur', value: 'ADMIN' }, { label: 'Super administrateur', value: 'SUPER_ADMIN' }] }], empty: 'Aucun administrateur disponible.' },
  jobs: { title: 'Offres', description: 'Supervisez les offres publiées sur JOBSINC.', endpoint: 'jobs', columns: [{ key: 'title', label: 'Titre' }, { key: 'companyName', label: 'Entreprise' }, { key: 'location', label: 'Localisation' }, { key: 'status', label: 'Statut' }, { key: 'applicationsCount', label: 'Candidatures' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Active', value: 'active' }, { label: 'Fermée', value: 'closed' }] }], empty: 'Aucune offre trouvée.' },
  applications: { title: 'Candidatures', description: 'Consultez les candidatures enregistrées sur la plateforme.', endpoint: 'applications', columns: [{ key: 'candidateName', label: 'Candidat' }, { key: 'companyName', label: 'Entreprise' }, { key: 'jobTitle', label: 'Offre' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Nouvelle', value: 'new' }, { label: 'En cours', value: 'review' }] }], empty: 'Aucune candidature trouvée.' },
  interviews: { title: 'Entretiens', description: 'Suivez les entretiens lorsqu’ils sont disponibles dans l’API.', endpoint: 'interviews', columns: [{ key: 'candidateName', label: 'Candidat' }, { key: 'companyName', label: 'Entreprise' }, { key: 'jobTitle', label: 'Offre' }, { key: 'scheduledAt', label: 'Date et heure' }, { key: 'status', label: 'Statut' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Planifié', value: 'scheduled' }, { label: 'Terminé', value: 'completed' }] }], empty: 'Aucun entretien trouvé.' },
  recruitments: { title: 'Recrutements', description: 'Analysez les recrutements finalisés exposés par le backend.', endpoint: 'recruitments', columns: [{ key: 'candidateName', label: 'Candidat' }, { key: 'companyName', label: 'Entreprise' }, { key: 'jobTitle', label: 'Poste' }, { key: 'createdAt', label: 'Date' }, { key: 'status', label: 'Statut' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Finalisé', value: 'completed' }] }], empty: 'Aucun recrutement trouvé.' },
  reports: { title: 'Signalements', description: 'Centralisez les signalements nécessitant une action de modération.', endpoint: 'reports', columns: [{ key: 'type', label: 'Type' }, { key: 'resource', label: 'Ressource' }, { key: 'reason', label: 'Motif' }, { key: 'priority', label: 'Priorité' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Nouveau', value: 'new' }, { label: 'En cours', value: 'in_progress' }, { label: 'Résolu', value: 'resolved' }] }], empty: 'Aucun signalement.' },
  moderation: { title: 'Modération', description: 'Examinez les contenus et comptes soumis à modération.', endpoint: 'moderation', columns: [{ key: 'type', label: 'Type' }, { key: 'resource', label: 'Ressource' }, { key: 'priority', label: 'Priorité' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Nouveau', value: 'new' }, { label: 'En cours', value: 'in_progress' }] }], empty: 'Aucun élément à modérer.' },
  analytics: { title: 'Statistiques', description: 'Consultez les indicateurs globaux fournis par les API Admin.', endpoint: 'analytics', columns: [{ key: 'label', label: 'Indicateur' }, { key: 'value', label: 'Valeur' }, { key: 'period', label: 'Période' }, { key: 'updatedAt', label: 'Mise à jour' }], filters: [{ key: 'period', label: 'Période', options: [{ label: '7 jours', value: '7d' }, { label: '30 jours', value: '30d' }, { label: '1 an', value: '1y' }] }], empty: 'Aucune statistique disponible.' },
  activity: { title: 'Activité', description: 'Suivez les événements de la plateforme et les actions administratives.', endpoint: 'activity', columns: [{ key: 'actor', label: 'Acteur' }, { key: 'action', label: 'Action' }, { key: 'resource', label: 'Ressource' }, { key: 'status', label: 'Résultat' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Résultat', options: [{ label: 'Succès', value: 'success' }, { label: 'Échec', value: 'failure' }] }], empty: 'Aucune activité récente.' },
  sessions: { title: 'Sessions', description: 'Surveillez les sessions actives lorsqu’elles sont exposées par l’API.', endpoint: 'sessions', columns: [{ key: 'userName', label: 'Utilisateur' }, { key: 'device', label: 'Appareil' }, { key: 'browser', label: 'Navigateur' }, { key: 'lastActivity', label: 'Dernière activité' }, { key: 'status', label: 'Statut' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Active', value: 'active' }, { label: 'Expirée', value: 'expired' }] }], empty: 'Aucune session active.' },
  notifications: { title: 'Notifications', description: 'Consultez les notifications système, sécurité et modération.', endpoint: 'notifications', columns: [{ key: 'title', label: 'Titre' }, { key: 'message', label: 'Message' }, { key: 'category', label: 'Catégorie' }, { key: 'read', label: 'État' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'category', label: 'Catégorie', options: [{ label: 'Système', value: 'system' }, { label: 'Sécurité', value: 'security' }, { label: 'Modération', value: 'moderation' }] }], empty: 'Aucune notification.' },
  system: { title: 'Santé du système', description: 'Surveillez les services dont l’état est fourni par le backend.', endpoint: 'system', columns: [{ key: 'label', label: 'Service' }, { key: 'status', label: 'État' }, { key: 'latency', label: 'Temps de réponse' }, { key: 'checkedAt', label: 'Vérification' }], filters: [{ key: 'status', label: 'État', options: [{ label: 'Opérationnel', value: 'operational' }, { label: 'Dégradé', value: 'degraded' }, { label: 'Indisponible', value: 'down' }] }], empty: 'État système indisponible.' },
  maintenance: { title: 'Maintenance', description: 'Consultez les opérations de maintenance réellement exposées par l’API.', endpoint: 'maintenance', columns: [{ key: 'label', label: 'Opération' }, { key: 'status', label: 'Statut' }, { key: 'startedAt', label: 'Début' }, { key: 'updatedAt', label: 'Mise à jour' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'En cours', value: 'in_progress' }, { label: 'Terminée', value: 'completed' }] }], empty: 'Aucune opération de maintenance.' },
  trends: { title: 'Tendances', description: 'Suivez l’évolution des indicateurs exposés par l’API Admin.', endpoint: 'trends', columns: [{ key: 'label', label: 'Indicateur' }, { key: 'value', label: 'Valeur' }, { key: 'period', label: 'Période' }, { key: 'trend', label: 'Évolution' }], filters: [{ key: 'period', label: 'Période', options: [{ label: '7 jours', value: '7d' }, { label: '30 jours', value: '30d' }, { label: '1 an', value: '1y' }] }], empty: 'Aucune tendance disponible.' },
  reportsAnalytics: { title: 'Rapports analytiques', description: 'Consultez les rapports fournis par le système Admin.', endpoint: 'reportsAnalytics', columns: [{ key: 'label', label: 'Rapport' }, { key: 'period', label: 'Période' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Disponible', value: 'ready' }, { label: 'En cours', value: 'processing' }] }], empty: 'Aucun rapport disponible.' },
  audit: { title: 'Journal d’audit', description: 'Consultez qui a fait quoi, sur quelle ressource et quand.', endpoint: 'audit', columns: [{ key: 'actor', label: 'Acteur' }, { key: 'action', label: 'Action' }, { key: 'resource', label: 'Ressource' }, { key: 'status', label: 'Résultat' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Résultat', options: [{ label: 'Succès', value: 'success' }, { label: 'Échec', value: 'failure' }] }], empty: 'Aucune entrée d’audit.' },
  logins: { title: 'Connexions', description: 'Surveillez les connexions réussies et échouées exposées par l’API.', endpoint: 'logins', columns: [{ key: 'userName', label: 'Utilisateur' }, { key: 'result', label: 'Résultat' }, { key: 'device', label: 'Appareil' }, { key: 'ip', label: 'Adresse IP' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'result', label: 'Résultat', options: [{ label: 'Succès', value: 'success' }, { label: 'Échec', value: 'failure' }] }], empty: 'Aucune connexion disponible.' },
  securityAlerts: { title: 'Alertes de sécurité', description: 'Examinez les événements de sécurité disponibles.', endpoint: 'securityAlerts', columns: [{ key: 'type', label: 'Type' }, { key: 'description', label: 'Description' }, { key: 'priority', label: 'Priorité' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'priority', label: 'Priorité', options: [{ label: 'Critique', value: 'critical' }, { label: 'Haute', value: 'high' }] }], empty: 'Aucune alerte de sécurité.' },
  content: { title: 'Contenus à modérer', description: 'Examinez les contenus signalés lorsqu’ils sont disponibles.', endpoint: 'content', columns: [{ key: 'type', label: 'Type' }, { key: 'resource', label: 'Ressource' }, { key: 'author', label: 'Auteur' }, { key: 'status', label: 'Statut' }, { key: 'createdAt', label: 'Date' }], filters: [{ key: 'status', label: 'Statut', options: [{ label: 'Nouveau', value: 'new' }, { label: 'Résolu', value: 'resolved' }] }], empty: 'Aucun contenu à modérer.' },
};

const normalize = (value: unknown) => value === undefined || value === null || value === '' ? '—' : String(value);

export default function AdminResourcePage({ section }: { section: string }) {
  const config = configs[section] || configs.activity;
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [query, setQuery] = useState(''); const [filters, setFilters] = useState<Record<string, string>>({}); const [page, setPage] = useState(1); const pageSize = 10;
  const [actionMsg, setActionMsg] = useState(''); const [confirmDelete, setConfirmDelete] = useState<Row | null>(null); const [busyId, setBusyId] = useState<string | number | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(false); try { setRows((await getAdminResource(config.endpoint)) as Row[] || []); } catch { setError(true); } finally { setLoading(false); } }, [config.endpoint]);
  useEffect(() => { const id = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(id); }, [load]);
  const filtered = useMemo(() => rows.filter((row) => Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase()) && Object.entries(filters).every(([key, filter]) => !filter || String(row[key] || '').toLowerCase() === filter.toLowerCase())), [rows, query, filters]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const isApplications = config.endpoint === 'applications';
  const isCompanies = config.endpoint === 'companies';
  const isUserRows = ['candidates', 'employees', 'administrators'].includes(config.endpoint);
  const isNotifications = config.endpoint === 'notifications';
  const smartRender = (key: string, row: Row) => {
    if (isNotifications && key === 'read') {
      return row.read ? <span className="admin-status-badge">Lue</span> : <span className="admin-status-badge admin-notif-unread">Non lue</span>;
    }
    if (isNotifications && key === 'category') {
      return <span className="admin-notif-category">{normalize(row.category)}</span>;
    }
    return normalize(row[key]);
  };
  const sectionLabel = isCompanies ? 'l’entreprise' : 'l’utilisateur';
  const userDisplayName = (row: Row) => String(row.name || row.email || '');
  const toggleUserBlock = async (row: Row) => {
    const targetId = row.userId !== undefined ? row.userId : row.id;
    if (targetId === undefined) return;
    setActionMsg(''); setBusyId(targetId);
    try { const block = !(row.isBlocked ?? false); await setAdminUserBlocked(String(targetId), block); setRows((current) => current.map((item) => item.id === row.id ? { ...item, isBlocked: block, status: block ? 'suspended' : 'active' } : item)); setActionMsg(block ? 'Compte suspendu.' : 'Compte réactivé.'); } catch (err) { setActionMsg(err instanceof Error ? err.message : 'Action impossible.'); } finally { setBusyId(null); }
  };
  const run = async (id: string | number | undefined, fn: (value: string) => Promise<unknown>, success: string) => {
    if (id === undefined) return;
    setActionMsg(''); setBusyId(id);
    try { await fn(String(id)); setRows((current) => current.filter((row) => row.id !== id)); setConfirmDelete(null); setActionMsg(success); } catch (err) { setActionMsg(err instanceof Error ? err.message : 'Action impossible.'); setConfirmDelete(null); } finally { setBusyId(null); }
  };
  const toggleCompanyBlock = async (row: Row) => {
    if (row.userId === undefined) return;
    setActionMsg(''); setBusyId(row.userId);
    try { const block = !(row.isBlocked ?? false); await setAdminUserBlocked(String(row.userId), block); setRows((current) => current.map((item) => item.id === row.id ? { ...item, isBlocked: block, status: block ? 'suspended' : 'active' } : item)); setActionMsg(block ? 'Entreprise suspendue.' : 'Entreprise réactivée.'); } catch (err) { setActionMsg(err instanceof Error ? err.message : 'Action impossible.'); } finally { setBusyId(null); }
  };
  const toggleCompanyApproval = async (row: Row, approved: boolean) => {
    if (row.id === undefined) return;
    setActionMsg(''); setBusyId(row.id);
    try { await setCompanyApproval(String(row.id), approved); setRows((current) => current.map((item) => item.id === row.id ? { ...item, isApproved: approved, status: approved ? 'active' : 'pending' } : item)); setActionMsg(approved ? 'Entreprise approuvée.' : 'Entreprise refusée.'); } catch (err) { setActionMsg(err instanceof Error ? err.message : 'Action impossible.'); } finally { setBusyId(null); }
  };
  const columns: AdminColumn<Row>[] = [
    ...config.columns.map((column) => ({ ...column, render: (row: Row) => smartRender(column.key, row) })),
    ...(isApplications ? [{ key: '__actions', label: 'Actions', render: (row: Row) => <div className="admin-row-actions" onClick={(event) => event.stopPropagation()} role="group" aria-label={`Actions sur la candidature de ${row.jobTitle || row.candidateName || ''}`}><Link className="admin-button admin-button-secondary admin-button-sm" href={`/admin/users/${row.userId}`}>Voir le candidat</Link><button className="admin-button admin-button-secondary admin-button-sm" disabled={busyId === row.id} onClick={() => run(row.id, rejectAdminApplication, 'Candidature bloquée (rejetée).')}>Bloquer</button><button className="admin-button admin-button-danger admin-button-sm" disabled={busyId === row.id} onClick={() => setConfirmDelete(row)}>Supprimer</button></div> }] : []),
    ...(isNotifications ? [{ key: '__open', label: '', render: (row: Row) => row.link ? <Link className="admin-button admin-button-secondary admin-button-sm" href={String(row.link)}>Ouvrir</Link> : <span className="admin-muted">—</span> }] : []),
    ...(isCompanies || isUserRows ? [{ key: '__detail', label: '', render: (row: Row) => <div className="admin-row-actions" onClick={(event) => event.stopPropagation()} role="group" aria-label={`Actions sur ${sectionLabel} ${userDisplayName(row)}`}>{isCompanies && row.isApproved === false ? <button className="admin-button admin-button-primary admin-button-sm" disabled={busyId === row.id} onClick={() => toggleCompanyApproval(row, true)}>Approuver</button> : null}<Link className="admin-button admin-button-secondary admin-button-sm" href={`/admin/users/${row.userId ?? row.id}`}>Voir le profil</Link><button className="admin-button admin-button-secondary admin-button-sm" disabled={busyId === (row.userId ?? row.id)} onClick={() => (isCompanies ? toggleCompanyBlock(row) : toggleUserBlock(row))}>{row.isBlocked ? 'Réactiver' : 'Bloquer'}</button><button className="admin-button admin-button-danger admin-button-sm" disabled={busyId === (row.userId ?? row.id)} onClick={() => setConfirmDelete(row)}>Supprimer</button></div> }] : []),
  ];
  return <section className="admin-resource-page"><AdminPageHeader title={config.title} description={config.description} actions={<AdminButton variant="secondary" disabled={!process.env[`NEXT_PUBLIC_ADMIN_${config.endpoint.toUpperCase()}_ENDPOINT`]}>Exporter</AdminButton>} />{actionMsg ? <div className="admin-alert admin-alert-success" role="status"><strong>{actionMsg}</strong></div> : null}<div className="admin-resource-toolbar"><label className="admin-users-search"><span>⌕</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder={`Rechercher dans ${config.title.toLowerCase()}...`} aria-label={`Rechercher dans ${config.title}`} /></label><AdminFilters filters={config.filters} values={filters} onChange={(key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); }} /></div><AdminDataTable columns={columns} rows={visible} loading={loading} error={error} onRetry={load} emptyTitle={config.empty} /><div className="admin-resource-pagination"><AdminPagination page={page} totalPages={pages} totalItems={filtered.length} onPageChange={setPage} /></div>{confirmDelete ? <div className="admin-modal-overlay" onClick={() => setConfirmDelete(null)}><div className="admin-modal" onClick={(event) => event.stopPropagation()}><p className="admin-kicker">Action irréversible</p><h3>{isApplications ? 'Supprimer cette candidature ?' : (isCompanies || isUserRows) ? 'Supprimer ce compte ?' : 'Supprimer ?'}</h3>{isCompanies ? <p>L’entreprise <strong>{String(confirmDelete.name || '')}</strong> et le compte <strong>{String(confirmDelete.email || '')}</strong> seront définitivement supprimés avec leurs offres et données associées. Cette action est irréversible.</p> : isUserRows ? <p>Le compte <strong>{String(confirmDelete.email || confirmDelete.name || '')}</strong> sera définitivement supprimé avec ses données associées. Cette action est irréversible.</p> : <p>La candidature de <strong>{String(confirmDelete.candidateName || '')}</strong> pour <strong>{String(confirmDelete.jobTitle || '')}</strong> sera définitivement supprimée, entretien et recrutement associés inclus.</p>}<div className="admin-modal-actions"><button className="admin-button admin-button-secondary" onClick={() => setConfirmDelete(null)}>Annuler</button><button className="admin-button admin-button-danger" onClick={() => (isCompanies || isUserRows) ? run(confirmDelete.userId !== undefined ? String(confirmDelete.userId) : undefined, deleteAdminUser, isCompanies ? 'Entreprise supprimée.' : 'Utilisateur supprimé.') : run(confirmDelete.id, deleteAdminApplication, 'Candidature supprimée.')}>Supprimer définitivement</button></div></div></div> : null}</section>;
}
