'use client';

import { useEffect, useRef, useState } from 'react';
import { Company, getCompanies } from '@/lib/api';

function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'E'; }
function CompanyPhoto({ company }: { company: Company }) { const sources = (company.images || []).map((image) => image.url).filter(Boolean); const [index, setIndex] = useState(0); useEffect(() => setIndex(0), [company.id]); if (!sources[index]) return <div className="company-photo-fallback" aria-label={`Initiales de ${company.name}`}>{initials(company.name)}</div>; return <img src={sources[index]} alt={`Présentation de ${company.name}`} onError={() => setIndex((current) => current + 1)} />; }

export default function CompanyCarousel() {
  const [companies, setCompanies] = useState<Company[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'empty' | 'error'>('loading'); const [active, setActive] = useState(0); const [paused, setPaused] = useState(false); const touchStart = useRef<number | null>(null);
  useEffect(() => { let activeRequest = true; getCompanies().then((data) => { if (!activeRequest) return; setCompanies(data); setState(data.length ? 'ready' : 'empty'); }).catch(() => { if (activeRequest) setState('error'); }); return () => { activeRequest = false; }; }, []);
  useEffect(() => { if (companies.length < 2 || paused) return; const timer = window.setInterval(() => setActive((current) => (current + 1) % companies.length), 5500); return () => window.clearInterval(timer); }, [companies.length, paused]);
  const move = (direction: number) => setActive((current) => (current + direction + companies.length) % companies.length); const company = companies[active];
  return <section id="companies" className="section section-tint"><div className="container"><div className="section-heading center"><div className="eyebrow">Un réseau qui avance</div><h2>Des entreprises recrutent avec JOBSINC</h2><p>Découvrez les entreprises qui développent leurs équipes sur la plateforme.</p></div>{state === 'loading' ? <div className="company-carousel-skeleton" aria-label="Chargement des entreprises"><i /><div><b /><b /><b /></div></div> : state === 'error' ? <div className="empty-state">Impossible de charger les entreprises.</div> : state === 'empty' ? <div className="empty-state">Aucune entreprise inscrite pour le moment.</div> : company && <div className="company-carousel" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onTouchStart={(event) => { touchStart.current = event.touches[0].clientX; }} onTouchEnd={(event) => { if (touchStart.current === null) return; const delta = event.changedTouches[0].clientX - touchStart.current; if (Math.abs(delta) > 35) move(delta > 0 ? -1 : 1); touchStart.current = null; }}><article className="company-feature-card" key={company.id}><div className="company-feature-image"><CompanyPhoto company={company} /></div><div className="company-feature-content"><span className="company-feature-kicker">Entreprises présentes sur JOBSINC</span><h3>{company.name}</h3><p className="company-feature-meta">{company.sector || 'Secteur non renseigné'}{company.location ? ` · ${company.location}` : ''}</p><p className="company-feature-description">{company.description || 'Cette entreprise développe actuellement son équipe avec JOBSINC.'}</p></div></article>{companies.length > 1 && <div className="company-carousel-controls"><button type="button" onClick={() => move(-1)} aria-label="Entreprise précédente">←</button><div className="company-carousel-dots">{companies.map((item, index) => <button type="button" key={item.id} className={index === active ? 'active' : ''} onClick={() => setActive(index)} aria-label={`Afficher ${item.name}`} />)}</div><button type="button" onClick={() => move(1)} aria-label="Entreprise suivante">→</button></div>}</div>}</div></section>;
}
